version: '3.1'

services:

  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: Webserver
    ports:
      - 81:80
    volumes:
      - ./src:/var/www/html/
 
  web2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Webserver2
    volumes:
      - ./web2/src:/var/www/html/
    ports:
      - 5051:80
    restart: always
     

  db:
     image: mysql
     container_name: Datenbank
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: tbz123. 
    

  adminer:
     image: adminer
     container_name: Admirer
     restart: always
     ports:
       - 8080:8080

  